name: Lighthouse CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  lighthouse:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build --if-present
    - name: Lighthouse CI Action
      uses: treosh/lighthouse-ci-action@v3
      with:
        configPath: '.github/lighthouse/.lighthouserc.json'
        temporaryPublicStorage: true
        uploadArtifacts: true
